config/routes.rb
# frozen_string_literal :true

Rails.application.routes.draw do
  resources :tour_packages
  resources :posts
  get "/pages", to: "pages#home"
  devise_for :users
  resources :customers
  resources :destinations
  resources :vehicles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "homepages#index"
end

app/models/tour_package.rb
class TourPackage < ApplicationRecord
  has_one_attached :image
  has_many_attached :pictures
  belongs_to :destination

  def image_as_thumbnail
    image.variant(resize_to_limit: [300, 300]).processed
  end

  def pictures_as_thumbnails
    pictures.map do |picture|
      picture.variant(resize_to_limit: [150, 150]).processed
    end
  end
end

app/controllers/tour_packages_controller.rb
# frozen_string_literal: true

# controller for tour packages
class TourPackagesController < ApplicationController
  before_action :set_tour_package, only: %i[show edit update destroy]
  before_action :destinations, only: %i[new edit]

  # GET /tour_packages or /tour_packages.json
  def index
    @tour_packages = TourPackage.all
  end

  # GET /tour_packages/1 or /tour_packages/1.json
  def show; end

  # GET /tour_packages/new
  def new
    @tour_package = TourPackage.new
  end

  # GET /tour_packages/1/edit
  def edit; end

  # POST /tour_packages or /tour_packages.json
  def create
    @tour_package = TourPackage.new(tour_package_params)
    @tour_package.destination = Destination.find(params[:destination_id])
    respond_to do |format|
      if @tour_package.save
        format.html { redirect_to @tour_package, notice: "Tour package was successfully created." }
        format.json { render :show, status: :created, location: @tour_package }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tour_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tour_packages/1 or /tour_packages/1.json
  def update
    respond_to do |format|
      if @tour_package.update(tour_package_params)
        format.html { redirect_to @tour_package, notice: "Tour package was successfully updated." }
        format.json { render :show, status: :ok, location: @tour_package }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tour_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tour_packages/1 or /tour_packages/1.json
  def destroy
    @tour_package.destroy
    respond_to do |format|
      format.html { redirect_to tour_packages_url, notice: "Tour package was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tour_package
    @tour_package = TourPackage.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tour_package_params
    params.require(:tour_package).permit(
      :name, :description, :destination_id, :duration, :price, :available_dates, :image
    )
  end

  def destinations
    @destinations = Destination.all
  end
end

app/helpers/tour_packages_helper.rb
module TourPackagesHelper
end

app/views/tour_packages/_form.html.erb
<%= form_with(model: tour_package) do |form| %>
  <% if tour_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour_package.errors.count, "error") %> prohibited this tour_package from being saved:</h2>

      <ul>
        <% tour_package.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :destination_id %>
    <select name="destination_id">
    <% @destinations.each do |destination| %>
    <option value="<%= destination.id %>"> <%= destination.name %></option>
    <% end %>
    </select>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :available_dates %>
    <%= form.text_field :available_dates, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :duration %>
    <%= form.text_field :duration, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form_control" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Package", class: "btn btn-lg btn-success "  %>
  </div>

<% end %>

app/views/tour_packages/edit.html.erb
<h1>Editing Tour Package</h1>

<%= render 'form', tour_package: @tour_package, destinations: @destinations %>

<%= link_to 'Show', @tour_package %> |
<%= link_to 'Back', tour_packages_path %>

app/views/tour_packages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tour Packages</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Place</th>
      <th>Duration</th>
      <th>Price</th>
      <th>Available dates</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tour_packages.each do |tour_package| %>
      <tr>
        <td><%= tour_package.name %></td>
        <td><%= tour_package.description %></td>
        <td><%= tour_package.destination.name %></td>
        <td><%= tour_package.duration %></td>
        <td><%= tour_package.price %></td>
        <td><%= tour_package.available_dates %></td>
        <td><%= link_to 'Show', tour_package %></td>
        <td><%= link_to 'Edit', edit_tour_package_path(tour_package) %></td>
        <td><%= link_to 'Destroy', tour_package, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Tour Package', new_tour_package_path, class: "btn btn-sucess" %>

app/views/tour_packages/new.html.erb
<h1>New Tour Package</h1>

<%= render 'form', tour_package: @tour_package, destinations: @destinations %>

<%= link_to 'Back', tour_packages_path %>

app/views/tour_packages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tour_package.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tour_package.description %>
</p>

<p>
  <strong>Place:</strong>
  <%= @tour_package.destination.name %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @tour_package.duration %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tour_package.price %>
</p>

<p>
  <strong>Available dates:</strong>
  <%= @tour_package.available_dates %>
</p>

<br />
<%= link_to image_tag(@tour_package.image_as_thumbnail), @tour_package.image if @tour_package.image.attached? %>
<br />


<%= link_to 'Edit', edit_tour_package_path(@tour_package) %> |
<%= link_to 'Back', tour_packages_path %>