config/routes.rb
# frozen_string_literal :true

Rails.application.routes.draw do
  resources :tour_packages
  resources :posts
  get "/pages", to: "pages#home"
  devise_for :users
  resources :customers
  resources :destinations
  resources :vehicles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "homepages#index"
end

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark"> 
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="/app/assets/images/logo.jpeg" width="30" height="30" alt="">
    </a>
    <a class="navbar-brand" href="/"><h1>Travel Nepal</h1></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%=  tour_packages_path(@tour_package) %>">Tour Packages</a>
          <li></li>
        </li>
       
        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Rentals
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
          <% @vehicles_types. each do |vehicle_type| %>
          <li><%= link_to vehicle_type, new_vehicle_path(vehicle_type: vehicle_type) %></li>
            <li><hr class="dropdown-divider"></li>
          <% end %>
          </ul>
        </li>
       

         <!--logins-->

        <div class = "nav-item">
          <% if current_user %>
          <%= link_to "SignOut", destroy_user_session_path, class: "nav-link", method: :delete %>
          <% else %>
          <%= link_to "SignIn", new_user_session_path, class: "nav-link" %> |  <%= link_to 'Sign up', new_user_registration_path, class: "nav-link"%>

          <% end %>

          <%= link_to "EditProfile",  edit_user_registration_path, class: "nav-link" %>
          
        </div>
      </ul> 

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

     

    </div>
  </div>
</nav>